### ISSUE TITLE
App Store Review Guidelines

### ISSUE THREAD

**Issue by ferologics** [shareup/wasm-interpreter-apple#15]
Is using this in line with app store review guidelines (for iOS apps)?

**Comment by atdrendel** [comment]
We haven't launched our product yet, but, from my reading of the guidelines, it's allowed to ship an interpreter as long as the code it interprets is shipped along with the app. It would be against the guidelines to allow user-created code to be used by WasmInterpreter.

**Comment by erikchi** [comment]
I'm wondering if there's any update on this? Thanks!

**Comment by atdrendel** [comment]
We've actually removed this dependency from our app because it was too slow for our use case. We were using a version of libsodium compiled to Wasm to handle encryption and decryption in our app. It worked very well, but the native C version was, naturally, much faster. Considering how critical cryptography is to our app, we couldn't ship the slower implementation. 

To be clear, for less processor-intensive use cases, I'd expect it would work very well.

That's a long way of saying that there's no update on whether or not the App Store would, in practice, accept apps using WasmInterpreter. As I mentioned above, though, using the interpreter is not against the rules of the App Store. You can't use it to run user-generated code, though. Any code you ship with the app should be fine, though.

**Comment by erikchi** [comment]
Thanks for the info! In this case, if you're using a version of libsodium compiled into WASM, then they are still running in the interpreter mode on iOS right? Why would it be faster than this dependency?

**Comment by atdrendel** [comment]
> Thanks for the info! In this case, if you're using a version of libsodium compiled into WASM, then they are still running in the interpreter mode on iOS right? Why would it be faster than this dependency?

Sorry. I was unclear. We're compiling the libsodium C code directly into our app. We've written a lightweight Swift wrapper around it, but that doesn't add much overhead. So, it's much, much faster than using libsodium compiled to Wasm and interpreted with `WasmInterpreter`.

**Comment by erikchi** [comment]
Ah, I see. Sorry about the misunderstanding. I thought you were still using the WASM version. So currently your app doesn't include any WASM part anymore? I'm also curious if you know a estimate of how much slow down is for the WASM version you used to have for the crypto operations (is the slow down so bad for something that's crypto heavy for example like a proxy)?

**Comment by atdrendel** [comment]
@erikziyunchi I conducted tests when we made the change, but I can't remember the exact numbers. Encrypting large files using libsodium's stream encryption went from many 10s of seconds down to significantly less than a second, if I remember correctly. So, the improvement was significant and made the choice to move to consuming the C library very, very easy.
