### ISSUE TITLE
Possible rename suggestion for your judgement

### ISSUE THREAD

**Issue by alejandroq** [shareup/wasm-interpreter-apple#2]
Hey team, this is a great little library. Tried it out using the tests as documentation and it worked. Given the lack of other WebAssembly related interpreter modules in SPM, WasmKit (or WASMKit) could be a possible name given the popularity of Kit suffixes in the space. If you disagree, feel free to close this "issue"! Thought I would surface this idea however.

**Comment by atdrendel** [comment]
Sorry, @alejandroq, I'm sorry I somehow missed this comment. _(GitHub notifications could use some...improvement 🙂️)_

I completely agree with you that the name `WasmInterpreter` leaves a lot to be desired. Mostly we chose it because it fits into our internal naming scheme. We have **a lot** of private repositories targeting a few different platforms, and we try to keep their names consistent.

Thanks for taking a look at the library, and please let me know if you have any other suggestions for how to improve it.
